### PR TITLE
12.0 imp l10n fr naf ape

### PR DESCRIPTION
**Pull request by remi-filament**
Adds in domain for contact to select only tags with no children (only NAF codes basically)
Adds a menu for APE codes, and adds a filter by default on tags so that APE codes are not displayed

### CODE REVIEW

**Comment by sbidoul** [comment]
Hi @remi-filament did you mean to do this PR against OCA/l10n-france instead of acsone?

**Comment by remi-filament** [comment]
Hi @sbidoul, since your module is not yet merged, i did it on yours directly so that if you want you can include it directly on your branch and PR.
I do not know how to fix Travis for your PR though...

**Comment by sbidoul** [comment]
Ah, I see, yes. Then the target of your PR should be branch `12.0-mig-l10n_fr_naf_ape`.

**Comment by remi-filament** [comment]
You are right, my mistake, I just opened PR #2 on correct branch

**Pull request closed without merging**
